services:
  - type: web
    name: agapept-backend
    env: node
    region: oregon # Choose a region closest to your users
    plan: free # or "starter" or "pro"
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: "4000"
      # Add other environment variables from your .env file here
      # - key: DATA_DIR
      #   value: /opt/render/project/src/data # Example path for persistent disk
      # - key: DB_PATH
      #   value: /opt/render/project/src/data/quiz.db
      # - key: LOG_PATH
      #   value: /opt/render/project/src/data/submissions_log.txt
      # - key: EMAIL_HOST
      #   value: your_smtp_host
      # - key: EMAIL_PORT
      #   value: "587"
      # - key: EMAIL_USER
      #   value: your_email_username
      # - key: EMAIL_PASS
      #   value: your_email_password
      # - key: EMAIL_TO
      #   value: recipient_email@example.com
    autoDeploy: true
    # For persistent storage on Render, uncomment and configure the disk section
    # disks:
    #   - name: agapept-data
    #     path: /opt/render/project/src/data
